In [10]:
import pandas as pd

In [11]:
import csv

In [12]:
csv_path = "employee_data.csv"
employees_df = pd.read_csv(csv_path)

employees_df.head()

   Emp ID              Name         DOB          SSN         State
0     232      John Mathews  1991-02-24  289-31-9165  North Dakota
1     533      Nathan Moore  1978-11-19  220-05-7469         Maine
2     256    Amanda Douglas  1990-01-08  564-27-6961         Idaho
3     189   Heather Andrews  1976-08-11  742-79-1797       Vermont
4     284  Daniel Hernandez  1976-07-22  656-01-7473      Colorado

In [13]:
# Placeholders for re-formatted contents
emp_ids = []
emp_first_names = []
emp_last_names = []
emp_dobs = []
emp_ssns = []
emp_states = []

In [30]:
# Dictionary of states with abbreviations
us_state_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

In [45]:
# Read the csv and convert it into a list of dictionaries
with open(csv_path) as emp_data:
    reader = csv.reader(emp_data)

    header = next(reader)

    # Loop through each row, re-grab each field and store in a new list
    for row in reader:

        # Grab emp_ids and store it into a list
        emp_ids = emp_ids + [row[0]]

        # Grab names, split them, and store them in a temporary variable
        split_name = row[1].split(" ")
        
         # Then save first and last name in separate lists
        emp_first_names.append(split_name[0])
        emp_last_names.append(split_name[1])
        
        # Grab DOB and reformat it
        split_DOB = row[2].split("-")
        emp_dobs.append(split_DOB[1] + "-" + split_DOB[2]+ "-" + split_DOB[0])
        
        # Grab SSN and reformat it
        split_SSN = row[3].split("-")
        emp_ssns.append("XXX-XX-"+ split_SSN[2])
                
       # Grab the states and use the dictionary to find the replacement
        emp_states.append(us_state_abbrev[row[4]])

# Zip all of the new lists together

zipped_list = zip(emp_ids, emp_first_names, emp_last_names, emp_dobs, emp_ssns, emp_states)

# Write all of the election data to csv
#Open the file using "write" mode. Specify the variable to hold the contents
output_path = "new_employee_data.csv"

with open(output_path, 'w', newline='') as csvfile:

    # Initialize csv.writer
    csvwriter = csv.writer(csvfile, lineterminator = "\n")
    
    # Write the first row (column headers)
    csvwriter.writerow(["Employee IDs", "Employee First Names", "Employee Last Names", "Employee Dates of Birth", "Employee SSNs", "Employee States"])
    csvwriter.writerow([x for x in zipped_list])